<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="AMICHAITO1-HHS" name="TestNG.sanityAllOptionsTest" tests="13" failures="0" timestamp="15 Jan 2020 18:00:42 GMT" time="394.366" errors="1">
  <testcase name="initialOfferQuestions" time="58.898" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="initialOfferScreen" time="44.811" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="finalOfferQuestions" time="82.541" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="finalOfferScreen" time="32.119" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="covers" time="5.426" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="payments" time="27.423" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="returnSteps" time="68.860" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="forwardSteps" time="74.288" classname="TestNG.sanityAllOptionsTest">
    <error type="java.lang.Exception" message="Failed in Email send by iiii.co.il">
      <![CDATA[java.lang.Exception: Failed in Email send by iiii.co.il
at TestNG.sanityAllOptionsTest.emailException(sanityAllOptionsTest.java:156)
at TestNG.sanityAllOptionsTest.forwardSteps(sanityAllOptionsTest.java:1223)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- forwardSteps -->
  <testcase name="callMeWizard2" classname="TestNG.sanityAllOptionsTest">
    <skipped/>
  </testcase> <!-- callMeWizard2 -->
  <testcase name="callMeWizard1" classname="TestNG.sanityAllOptionsTest">
    <skipped/>
  </testcase> <!-- callMeWizard1 -->
  <testcase name="thankYouPage" classname="TestNG.sanityAllOptionsTest">
    <skipped/>
  </testcase> <!-- thankYouPage -->
  <testcase name="registeredAccount" classname="TestNG.sanityAllOptionsTest">
    <skipped/>
  </testcase> <!-- registeredAccount -->
  <testcase name="iframeCreditGuard" classname="TestNG.sanityAllOptionsTest">
    <skipped/>
  </testcase> <!-- iframeCreditGuard -->
</testsuite> <!-- TestNG.sanityAllOptionsTest -->
